// Builds hooks/tool-schemas.mjs: JSON input schemas for Claude Code's built-in tools, read from the
// tool types the engine writes for a mod (.claude-plugin/types/claude-code-tools/index.d.ts).
// Free backup answers model steps itself, and $.tool.list() gives names and descriptions but no
// schemas, so the free model gets these. Rerun after a Claude Code update:
//   node scripts/tool-schemas.mjs <tools index.d.ts> <path to the typescript package>
import { createRequire } from 'node:module';
import { readFileSync, writeFileSync } from 'node:fs';

const [typesPath, typescriptPath] = process.argv.slice(2);
if (!typesPath || !typescriptPath) {
  console.error('usage: node scripts/tool-schemas.mjs <claude-code-tools/index.d.ts> <typescript package dir>');
  process.exit(2);
}
const ts = createRequire(import.meta.url)(typescriptPath);
const source = ts.createSourceFile(typesPath, readFileSync(typesPath, 'utf8'), ts.ScriptTarget.Latest, true);

function docOf(node) {
  const ranges = ts.getLeadingCommentRanges(source.text, node.getFullStart()) || [];
  const doc = ranges.map(range => source.text.slice(range.pos, range.end)).filter(text => text.startsWith('/**')).pop();
  if (!doc) return undefined;
  const text = doc.replace(/^\/\*\*|\*\/$/g, '').split('\n').map(line => line.replace(/^\s*\*\s?/, '')).join(' ').replace(/\s+/g, ' ').trim();
  return text.startsWith('@internal') ? undefined : text || undefined;
}

function schemaOf(type) {
  if (!type) return {};
  switch (type.kind) {
    case ts.SyntaxKind.StringKeyword: return { type: 'string' };
    case ts.SyntaxKind.NumberKeyword: return { type: 'number' };
    case ts.SyntaxKind.BooleanKeyword: return { type: 'boolean' };
    case ts.SyntaxKind.AnyKeyword:
    case ts.SyntaxKind.UnknownKeyword: return {};
    case ts.SyntaxKind.ParenthesizedType: return schemaOf(type.type);
    case ts.SyntaxKind.ArrayType: return { type: 'array', items: schemaOf(type.elementType) };
    case ts.SyntaxKind.LiteralType: {
      const literal = type.literal;
      if (literal.kind === ts.SyntaxKind.StringLiteral) return { type: 'string', enum: [literal.text] };
      if (literal.kind === ts.SyntaxKind.NumericLiteral) return { type: 'number', enum: [Number(literal.text)] };
      if (literal.kind === ts.SyntaxKind.TrueKeyword || literal.kind === ts.SyntaxKind.FalseKeyword) return { type: 'boolean' };
      return {};
    }
    case ts.SyntaxKind.UnionType: {
      const parts = type.types.map(schemaOf);
      if (parts.every(part => part.type === 'string' && part.enum)) return { type: 'string', enum: parts.flatMap(part => part.enum) };
      return { anyOf: parts };
    }
    case ts.SyntaxKind.TypeReference: {
      const name = type.typeName.getText(source);
      if ((name === 'Array' || name === 'ReadonlyArray') && type.typeArguments?.length) return { type: 'array', items: schemaOf(type.typeArguments[0]) };
      if (name === 'Record') return { type: 'object' };
      return {};
    }
    case ts.SyntaxKind.TypeLiteral: return objectSchema(type.members);
    default: return {};
  }
}

function objectSchema(members) {
  const properties = {};
  const required = [];
  for (const member of members) {
    if (!ts.isPropertySignature(member) || !member.name) continue;
    const name = member.name.getText(source).replace(/^["']|["']$/g, '');
    const schema = schemaOf(member.type);
    const description = docOf(member);
    properties[name] = description ? { ...schema, description } : schema;
    if (!member.questionToken) required.push(name);
  }
  return required.length ? { type: 'object', properties, required } : { type: 'object', properties };
}

let inputs;
source.forEachChild(function visit(node) {
  if (ts.isInterfaceDeclaration(node) && node.name.text === 'BuiltinToolInputs') inputs = node;
  else node.forEachChild(visit);
});
if (!inputs) throw new Error('BuiltinToolInputs not found');

const schemas = {};
for (const member of inputs.members) {
  if (!ts.isPropertySignature(member) || !member.type || !ts.isTypeLiteralNode(member.type)) continue;
  schemas[member.name.getText(source).replace(/^["']|["']$/g, '')] = objectSchema(member.type.members);
}
const out = new URL('../hooks/tool-schemas.mjs', import.meta.url);
writeFileSync(out, `// Generated by scripts/tool-schemas.mjs from Claude Code's built-in tool types. Do not edit.\nexport const TOOL_SCHEMAS = ${JSON.stringify(schemas)};\n`);
console.log(`${Object.keys(schemas).length} tool schemas written`);
